name: Build wasm package

on:
  push:
    tags:
      - "*"

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
  build:
    name: Build
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
      - name: Authenticate with private NPM package
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.SBC_SOLVER_ENGINE_GITHUB_TOKEN }}" >> ./.npmrc
      - name: Install
        run: yarn install --prefer-offline --force
      - name: Set up env variables
        run: echo "${{ secrets.ENV_FILE }}" > .env
      - name: Build chrome extension
        run: ./scripts/build_extension.sh
      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension
          path: ./chrome_extension
          retention-days: 1
  release:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: chrome-extension
          path: ./chrome_extension
      - name: Build artifact
        uses: thedoctor0/zip-release@0.7.5
        with:
          path: "./chrome_extension"
          type: "zip"
          filename: "sbc_solver.zip"
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          makeLatest: True
          artifacts: "sbc_solver.zip"
