name: Lint

on:
  workflow_call:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
      - name: Authenticate with private NPM package
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.SBC_SOLVER_ENGINE_GITHUB_TOKEN }}" >> ./.npmrc
      - name: Install
        run: yarn install --prefer-offline --force
      - name: Prettier
        run: yarn prettier
      - name: Eslint
        run: yarn eslint
