name: Lint

on:
  workflow_call:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '19'
          cache: 'yarn'
      - name: Install
        run: yarn install --prefer-offline --force
      - name: Prettier
        run: yarn prettier
      - name: Eslint
        run: yarn eslint